-- EnemyData.lua
-- Stats and behaviour profiles for all enemy types

local EnemyData = {
    Scout = {
        displayName    = "Scout Bot",
        maxHp          = 45,
        speed          = 12,
        attackType     = "ranged",
        attackDamage   = 10,
        attackRange    = 22,
        attackCooldown = 2.0,
        projectileSpeed = 55,
        detectionRange = 40,
        color          = Color3.fromRGB(100, 150, 220),
        bodySize       = Vector3.new(2, 3, 2),
        score          = 50,
    },
    Drone = {
        displayName    = "Patrol Drone",
        maxHp          = 30,
        speed          = 16,
        attackType     = "ranged",
        attackDamage   = 8,
        attackRange    = 18,
        attackCooldown = 1.6,
        projectileSpeed = 70,
        detectionRange = 50,
        floats         = true,   -- hovers 6 studs above its spawn surface
        hoverHeight    = 6,
        color          = Color3.fromRGB(160, 210, 255),
        bodySize       = Vector3.new(3, 1.5, 3),
        score          = 40,
    },
    Crawler = {
        displayName    = "Alien Crawler",
        maxHp          = 65,
        speed          = 18,
        attackType     = "melee",
        attackDamage   = 18,
        attackRange    = 5,
        attackCooldown = 0.9,
        detectionRange = 35,
        color          = Color3.fromRGB(55, 180, 75),
        bodySize       = Vector3.new(3, 2, 3),
        score          = 60,
    },
    Spitter = {
        displayName    = "Acid Spitter",
        maxHp          = 55,
        speed          = 7,
        attackType     = "ranged",
        attackDamage   = 12,
        dotDamage      = 6,    -- damage per second for 3s
        dotDuration    = 3,
        attackRange    = 28,
        attackCooldown = 2.5,
        projectileSpeed = 45,
        detectionRange = 42,
        color          = Color3.fromRGB(120, 255, 70),
        bodySize       = Vector3.new(2.5, 2.5, 2.5),
        score          = 70,
    },
    Grunt = {
        displayName    = "Grunt Bot",
        maxHp          = 85,
        speed          = 10,
        attackType     = "melee",
        attackDamage   = 24,
        attackRange    = 6,
        attackCooldown = 1.2,
        detectionRange = 28,
        color          = Color3.fromRGB(220, 120, 50),
        bodySize       = Vector3.new(2.5, 4, 2.5),
        score          = 80,
    },
    Heavy = {
        displayName    = "Heavy Mech",
        maxHp          = 160,
        speed          = 6,
        attackType     = "melee",
        attackDamage   = 38,
        attackRange    = 8,
        attackCooldown = 2.0,
        detectionRange = 24,
        color          = Color3.fromRGB(180, 88, 28),
        bodySize       = Vector3.new(4, 5, 4),
        armorReduction = 0.3,  -- 30% damage reduction
        score          = 120,
    },
}

return EnemyData
