-- EnemyData.lua
-- Stats and behaviour profiles for all enemy types

local EnemyData = {
    -- ── Original enemies ──────────────────────────────────────────────────────
    Scout = {
        displayName    = "Scout Bot",
        maxHp          = 45,
        speed          = 12,
        attackType     = "ranged",
        attackDamage   = 10,
        attackRange    = 22,
        attackCooldown = 2.0,
        projectileSpeed = 55,
        detectionRange = 40,
        color          = Color3.fromRGB(100, 150, 220),
        bodySize       = Vector3.new(2, 3, 2),
        score          = 50,
    },
    Drone = {
        displayName    = "Patrol Drone",
        maxHp          = 30,
        speed          = 16,
        attackType     = "ranged",
        attackDamage   = 8,
        attackRange    = 18,
        attackCooldown = 1.6,
        projectileSpeed = 70,
        detectionRange = 50,
        floats         = true,
        hoverHeight    = 6,
        color          = Color3.fromRGB(160, 210, 255),
        bodySize       = Vector3.new(3, 1.5, 3),
        score          = 40,
    },
    Crawler = {
        displayName    = "Alien Crawler",
        maxHp          = 65,
        speed          = 18,
        attackType     = "melee",
        attackDamage   = 18,
        attackRange    = 5,
        attackCooldown = 0.9,
        detectionRange = 35,
        color          = Color3.fromRGB(55, 180, 75),
        bodySize       = Vector3.new(3, 2, 3),
        score          = 60,
    },
    Spitter = {
        displayName    = "Acid Spitter",
        maxHp          = 55,
        speed          = 7,
        attackType     = "ranged",
        attackDamage   = 12,
        dotDamage      = 6,
        dotDuration    = 3,
        attackRange    = 28,
        attackCooldown = 2.5,
        projectileSpeed = 45,
        detectionRange = 42,
        color          = Color3.fromRGB(120, 255, 70),
        bodySize       = Vector3.new(2.5, 2.5, 2.5),
        score          = 70,
    },
    Grunt = {
        displayName    = "Grunt Bot",
        maxHp          = 85,
        speed          = 10,
        attackType     = "melee",
        attackDamage   = 24,
        attackRange    = 6,
        attackCooldown = 1.2,
        detectionRange = 28,
        color          = Color3.fromRGB(220, 120, 50),
        bodySize       = Vector3.new(2.5, 4, 2.5),
        score          = 80,
    },
    Heavy = {
        displayName    = "Heavy Mech",
        maxHp          = 160,
        speed          = 6,
        attackType     = "melee",
        attackDamage   = 38,
        attackRange    = 8,
        attackCooldown = 2.0,
        detectionRange = 24,
        color          = Color3.fromRGB(180, 88, 28),
        bodySize       = Vector3.new(4, 5, 4),
        armorReduction = 0.30,
        score          = 120,
    },

    -- ── New enemies ───────────────────────────────────────────────────────────

    -- Long-range glass cannon; nearly stationary when targeting
    SniperBot = {
        displayName    = "Sniper Bot",
        maxHp          = 40,
        speed          = 4,
        attackType     = "ranged",
        attackDamage   = 50,
        attackRange    = 65,
        attackCooldown = 4.0,
        projectileSpeed = 130,
        detectionRange = 75,
        color          = Color3.fromRGB(130, 165, 210),
        bodySize       = Vector3.new(2, 3.5, 2),
        score          = 95,
    },

    -- Fast assassin that teleports toward its prey
    Phantom = {
        displayName     = "Phantom",
        maxHp           = 38,
        speed           = 24,
        attackType      = "melee",
        attackDamage    = 22,
        attackRange     = 4,
        attackCooldown  = 0.7,
        detectionRange  = 48,
        teleports       = true,
        teleportCooldown = 3.5,
        teleportRange   = 18,
        color           = Color3.fromRGB(160, 90, 220),
        bodySize        = Vector3.new(1.5, 3, 1.5),
        score           = 90,
    },

    -- Melee charger; speed and damage multiply when HP < 50%
    Berserker = {
        displayName    = "Berserker",
        maxHp          = 80,
        speed          = 13,
        rageSpeed      = 38,
        enrageBelow    = 0.5,
        attackType     = "melee",
        attackDamage   = 26,
        attackRange    = 5,
        attackCooldown = 0.75,
        detectionRange = 38,
        color          = Color3.fromRGB(200, 55, 30),
        bodySize       = Vector3.new(2.5, 3.5, 2.5),
        score          = 95,
    },

    -- Floating drone that lobs slow explosive shots
    Bomber = {
        displayName    = "Bomber Bot",
        maxHp          = 60,
        speed          = 7,
        attackType     = "ranged",
        attackDamage   = 32,
        attackRange    = 32,
        attackCooldown = 3.2,
        projectileSpeed = 32,
        detectionRange = 46,
        floats         = true,
        hoverHeight    = 9,
        color          = Color3.fromRGB(230, 160, 25),
        bodySize       = Vector3.new(3, 2, 3),
        score          = 105,
    },

    -- Bulky melee unit with heavy ranged armor; punishes facetanking
    Shielder = {
        displayName    = "Shielder",
        maxHp          = 130,
        speed          = 7,
        attackType     = "melee",
        attackDamage   = 32,
        attackRange    = 7,
        attackCooldown = 1.5,
        detectionRange = 26,
        armorReduction = 0.60,
        color          = Color3.fromRGB(90, 120, 180),
        bodySize       = Vector3.new(3, 4.5, 1.5),
        score          = 115,
    },

    -- Stationary rapid-fire emplacement; does not chase player
    Turret = {
        displayName    = "Defense Turret",
        maxHp          = 95,
        speed          = 0,
        attackType     = "ranged",
        attackDamage   = 14,
        attackRange    = 52,
        attackCooldown = 0.75,
        projectileSpeed = 95,
        detectionRange = 58,
        isStationary   = true,
        color          = Color3.fromRGB(75, 80, 100),
        bodySize       = Vector3.new(3, 2.5, 3),
        score          = 75,
    },

    -- Tiny, extremely fast swarmer; always comes in numbers
    Swarm = {
        displayName    = "Void Swarm",
        maxHp          = 18,
        speed          = 30,
        attackType     = "melee",
        attackDamage   = 8,
        attackRange    = 3,
        attackCooldown = 0.5,
        detectionRange = 52,
        color          = Color3.fromRGB(30, 185, 95),
        bodySize       = Vector3.new(1.2, 1.2, 1.2),
        score          = 25,
    },

    -- Massive armored brute; very slow but hits like a freight train
    Juggernaut = {
        displayName    = "Juggernaut",
        maxHp          = 340,
        speed          = 4,
        attackType     = "melee",
        attackDamage   = 60,
        attackRange    = 9,
        attackCooldown = 2.6,
        detectionRange = 22,
        armorReduction = 0.45,
        color          = Color3.fromRGB(130, 55, 18),
        bodySize       = Vector3.new(5.5, 6.5, 5.5),
        score          = 200,
    },

    -- ── Wave 2 enemies ────────────────────────────────────────────────────────

    -- Very fast shadow assassin that teleports to close gaps
    ShadowWraith = {
        displayName      = "Shadow Wraith",
        maxHp            = 35,
        speed            = 32,
        attackType       = "melee",
        attackDamage     = 20,
        attackRange      = 4,
        attackCooldown   = 0.5,
        detectionRange   = 55,
        teleports        = true,
        teleportCooldown = 2.5,
        teleportRange    = 20,
        color            = Color3.fromRGB(60, 20, 80),
        bodySize         = Vector3.new(1.5, 3.5, 1.5),
        score            = 85,
    },

    -- Shoots from range then teleports to reposition
    VoidStalker = {
        displayName      = "Void Stalker",
        maxHp            = 55,
        speed            = 10,
        attackType       = "ranged",
        attackDamage     = 30,
        attackRange      = 45,
        attackCooldown   = 2.8,
        projectileSpeed  = 90,
        detectionRange   = 60,
        teleports        = true,
        teleportCooldown = 5,
        teleportRange    = 25,
        color            = Color3.fromRGB(80, 30, 120),
        bodySize         = Vector3.new(2, 3, 2),
        score            = 100,
    },

    -- Fast flying melee attacker
    RazorWing = {
        displayName    = "Razor Wing",
        maxHp          = 42,
        speed          = 22,
        attackType     = "melee",
        attackDamage   = 16,
        attackRange    = 4,
        attackCooldown = 0.65,
        detectionRange = 48,
        floats         = true,
        hoverHeight    = 8,
        color          = Color3.fromRGB(200, 80, 40),
        bodySize       = Vector3.new(3, 1, 3),
        score          = 75,
    },

    -- Slow but hardy ranged caster
    Necromancer = {
        displayName    = "Necromancer",
        maxHp          = 70,
        speed          = 6,
        attackType     = "ranged",
        attackDamage   = 18,
        attackRange    = 35,
        attackCooldown = 3.5,
        projectileSpeed = 50,
        detectionRange = 50,
        color          = Color3.fromRGB(50, 180, 100),
        bodySize       = Vector3.new(2, 4, 2),
        score          = 130,
    },

    -- Heavy armored melee unit with damage-reducing shield
    MechKnight = {
        displayName    = "Mech Knight",
        maxHp          = 200,
        speed          = 8,
        attackType     = "melee",
        attackDamage   = 45,
        attackRange    = 8,
        attackCooldown = 1.4,
        detectionRange = 30,
        armorReduction = 0.35,
        color          = Color3.fromRGB(80, 100, 140),
        bodySize       = Vector3.new(3, 5, 3),
        score          = 160,
    },

    -- Rushes in and deals huge explosion damage once; effectively a living bomb
    SpiderMine = {
        displayName    = "Spider Mine",
        maxHp          = 25,
        speed          = 20,
        attackType     = "melee",
        attackDamage   = 55,
        attackRange    = 3,
        attackCooldown = 99,
        detectionRange = 35,
        color          = Color3.fromRGB(220, 60, 20),
        bodySize       = Vector3.new(1.5, 1, 1.5),
        score          = 50,
    },

    -- Massive slow crystalline tank with extreme armor
    CrystalGolem = {
        displayName    = "Crystal Golem",
        maxHp          = 280,
        speed          = 5,
        attackType     = "melee",
        attackDamage   = 50,
        attackRange    = 9,
        attackCooldown = 2.2,
        detectionRange = 22,
        armorReduction = 0.5,
        color          = Color3.fromRGB(100, 200, 255),
        bodySize       = Vector3.new(4.5, 6, 4.5),
        score          = 180,
    },

    -- Ranged acid attacker that leaves damaging trails
    AcidCrawler = {
        displayName    = "Acid Crawler",
        maxHp          = 60,
        speed          = 15,
        attackType     = "ranged",
        attackDamage   = 10,
        dotDamage      = 8,
        dotDuration    = 4,
        attackRange    = 25,
        attackCooldown = 2.0,
        projectileSpeed = 40,
        detectionRange = 40,
        color          = Color3.fromRGB(80, 220, 60),
        bodySize       = Vector3.new(3, 2, 3),
        score          = 80,
    },
}

return EnemyData
